name: Readme Stats Cards

on:
  schedule:
    - cron: "20 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p assets/stats

      - name: Download GitHub stats card
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=leeehvinicius&show_icons=true&theme=radical&hide_border=true" \
          -o assets/stats/github-stats.svg

      - name: Download Top languages card
        run: |
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=leeehvinicius&layout=compact&theme=radical&hide_border=true&langs_count=8&card_width=320" \
          -o assets/stats/top-langs.svg


      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/stats/*.svg
          git commit -m "chore: update readme stats cards" || echo "No changes to commit"
          git push
